name: Deploy current version
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Fetch latest version tarball
        run: |
          CURRENT_VERSION=$(head -n 1 CURRENT_VERSION)
          echo $CURRENT_VERSION
          npm pack @entur/enki@$CURRENT_VERSION
          tar -xf entur-enki-$CURRENT_VERSION.tgz
          ls -lah package
