name: Check latest version
'on':
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config --global user.name 'Latest version bot'
          git config --global user.email 'latest-version-bot@entur.org'
      - name: Check latest version
        run: |
          LATEST_VERSION=$(curl -L \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.npm.install-v1+json" \
            https://npm.pkg.github.com/@entur/enki \
            | jq -r '.["dist-tags"].latest')
          echo $LATEST_VERSION
          CURRENT_VERSION=$(head -n 1 CURRENT_VERSION)
          echo $CURRENT_VERSION
          #if [[ "$LATEST_VERSION" != "$CURRENT_VERSION" ]]; then
          #  # Update CURRENT_VERSION
          #  echo $LATEST_VERSION > CURRENT_VERSION
          #  git add CURRENT_VERSION
          #  git commit -m 'Updated CURRENT_VERSION'
          #  git push origin main
          #fi